{"name": "Test Authorized endpoint - Failed Authentication", "status": "failed", "statusDetails": {"message": "AssertionError: Unexpected response status code: 502\nassert False", "trace": "@allure.title(\"Test Authorized endpoint - Failed Authentication\")\n    def test_authorized_failure():\n        with allure.step(\"Sending POST request to Authorized endpoint with invalid credentials\"):\n            response = requests.post(f\"{BASE_URL}/Authorized\", json=invalid_user)\n    \n        if response.status_code in [400, 404]:\n            assert response.json() == {\"code\": \"1207\", \"message\": \"User not found!\"}, f\"Ошибка: {response.json()}\"\n        else:\n>           assert False, f\"Unexpected response status code: {response.status_code}\"\nE           AssertionError: Unexpected response status code: 502\nE           assert False\n\nswagger_test.py:32: AssertionError"}, "steps": [{"name": "Sending POST request to Authorized endpoint with invalid credentials", "status": "passed", "start": 1715447774863, "stop": 1715447775703}], "start": 1715447774863, "stop": 1715447775703, "uuid": "e6cbfd9e-04a7-48e0-97ac-88c2e0b287e5", "historyId": "331f821270927c9d49ee8e0f347ddc90", "testCaseId": "331f821270927c9d49ee8e0f347ddc90", "fullName": "swagger_test#test_authorized_failure", "labels": [{"name": "suite", "value": "swagger_test"}, {"name": "host", "value": "Romidamaru"}, {"name": "thread", "value": "14080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "swagger_test"}]}